language: java
sudo: required
services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=3.5

install:
  - docker-compose build

script:
  - docker-compose run btls ./gradlew check

after_success:
  - bash <(curl -s https://codecov.io/bash)