language: java
sudo: required
services:
  - docker

env:  
  - DOCKER_COMPOSE_VERSION=3.5

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose --version
  - docker-compose build

script:
  - docker-compose run btls ./gradlew check

after_success:
  - docker-compose run btls apt-get update
  - docker-compose run btls apt-get install curl
  - docker-compose run btls bash <(curl -s https://codecov.io/bash)